### PR TITLE
unwrap comments text.

### PR DESCRIPTION
**Pull request by ghost**
Hello,

in the ticgitweb interface all the text in comments is wrapped, ignoring empty new empty lines and paragraphs.

I'm new to ticgit and I don't know it the wrapping it's intentional for security reasons or any other reason, but I propose this fix. It changes the css to treat text comments as pre and puts a horizontal scrollbar if the line is too long.

Seems to work here.

### CODE REVIEW

**Comment by jeffWelling** [comment]
When I tested this out on my machine, I'm not sure I liked the outcome. What I did was copied in two paragraphs of lorem ipsum, but they came out as two ridiculously long lines.  Granted, it's an improvement from before your patch which merges the two paragraphs together into one equally ridiculous one, but I wonder if there's a happier medium. Is there a way to not have the paragraphs merged while having sentences wrap?

Also, if the patch behaves differently for you, let me know. It could be that it already does wrap sentences for you.

**Comment by jeffWelling** [comment]
Full disclosure, I'm not intimately familiar with CSS at all, this is an honest question not a joke lol

**Comment by jeffWelling** [comment]
Or perhaps a runtime argument which would enable this behavior. Thoughts?

**Comment by ghost** [comment]
I'm not familiar with css either, nor ruby or sinatra. I got those lines from trying. Yes, the long bar for long phrases is ugly and breaks the previous behavior of breaking long lines. Maybe this is too invasive. I would propose to drop this patch, that only works for code snippets in comments.

My problem was the ignoring new lines. I find the way ticgitweb wraps the whole text ugly in the webpage, mainly because I use the text editor in the command line and use code snippets on the comments. It all wraps up in the webpage...

From reading http://stackoverflow.com/questions/5636821/including-local-js-and-css-files-in-local-sinatra-developement I wonder if ticgitweb also can use a local css. That would work for me. I will have to try this when I have time.

**Comment by jeffWelling** [comment]
Well your right that the way that it does it right now (merging everything together into one paragraph) is quite awful for longer comments, so I'll poke around and see if I can find that happy medium. When I do, I'll release a new hotfix version with it.

**Comment by ghost** [comment]
Thank you for your attention, Jeff.

On Thu, Mar 8, 2012 at 5:29 PM, Jeff Welling
reply@reply.github.com
wrote:

**Pull request closed without merging**
