### PR TITLE
Fix Base's calling of git.lib.full_log_commits.

### PR DESCRIPTION
**Pull request by duckdalbe**
Argument must be a hash.

### CODE REVIEW

**Comment by jeffWelling** [comment]
Hm.  Good catch. I hadn't noticed that when I was writing that line because I wasn't concerned with the output of the function, just that it exploded when you had a git repo with no commits in it and that it didn't explode when the same repo had more than zero commits in it.
It doesn't seem to be a show-stopper, at least on my end, so I'll include it in the next version. Please do let me know if it's giving you problems and it will be pushed out as a hotfix immediately.
Thanks for pointing this out to me!
Jeff.

**Comment by jeffWelling** [comment]
This has been cherry-picked into the 'next' branch in my repository.  When the next version of TicGit-ng is published it will come from this branch and at that time this commit will be merged into master, so I'm going to close the pull request for now.  If this is something that is giving you trouble then please let me know or reopen the pull request and it will be expedited.
Thanks again,
Jeff.

**Comment by duckdalbe** [comment]
Just to inform you (you can re-close the issue again, right away): For me this patch was neccessary to getting started in an existing repository with quite some commits in it. Might be this is due to some curious circumstances on my side, if no one else complains. But in my setting it was a show-stopper.

**Comment by jeffWelling** [comment]
I see, I will push out a hotfix as soon as possible.

In order to write a test for this, can I ask approximately how many commits are in this large repository?

**Comment by duckdalbe** [comment]
$> git log --oneline | wc -l
440

**Comment by jeffWelling** [comment]
Hm, I just tried `ti init` and even `ti new` on a clone of the linux kernel git repository, which had 323124 commits when I tested it, and it ran fine for me.  Did you run `git log --oneline...` on the 'ticgit' branch or on the actual source code containing branches? 

My first guess was that this was related to the size of the repository but since my initial tests seem to indicate otherwise I think we should try to track down what caused the failure on your end and why this patch fixed it.

**Comment by jandechent** [comment]
I created a new reporitory with one single file. If I run `ti init` I get the error, but the prosed pull request solved these issues. 
`git.lib.full_log_commits` is containing data (printed to cmd with `puts`):

> {"sha"=>"31562aeec5d4345f09ff9e7269dcc03251b0097f", "message"=>"First\n", "paren
> t"=>[], "commit"=>"31562aeec5d4345f09ff9e7269dcc03251b0097f", "tree"=>"ea5446193

*Windows 7
*TigGit 1.0.2.16
*GemGit 1.2.5
*Git 1.7.11.msysgit.1
*ruby 1.9.3p194

**Comment by jeffWelling** [comment]
I'm pushing out a a hotfix for this now, but I'd like to continue to troubleshoot this to understand why it's failing for other people but not for me, and I could use your help if you have some time.

You mention the error, could you copy paste the error output?

**Comment by jeffWelling** [comment]
I'm using Ruby 1.8, I will test 1.9, perhaps that is one of the clues.

duckdalbe are you using Ruby 1.9 as well?

**Comment by jeffWelling** [comment]
I've just pushed out a new version, 1.0.2.17, with the fix for this included. Investigation into the root cause is on-going so that I can write a test can be written to detect regressions. I will mark this issue as closed but if you can help find the root cause please do continue commenting.

**Comment by duckdalbe** [comment]
I do.

Sorry for my lag, I'm on vacation and can spend more time on this only
from the end of october on.

**Comment by jeffWelling** [comment]
I just ran the TicGit-ng tests with Ruby 1.9 via RVM and every single test failed, so I am able to replicate this bug. Now I can write a test for it if necessary.

**Pull request closed without merging**
